### ISSUE TITLE
Error in the private service

### ISSUE THREAD

**Issue by baogorek** [kjmerf/hello_cb_pro#5]
When I run 
```
# build and run the private service
docker-compose up --build --remove-orphans private
```

I get
```
Starting hello_cb_pro_private_1 ... done
Attaching to hello_cb_pro_private_1
private_1       | Traceback (most recent call last):
private_1       |   File "/app/private.py", line 4, in <module>
private_1       |     from cbt.private_client import PrivateClient
private_1       |   File "/app/cbt/private_client.py", line 5, in <module>
private_1       |     from cbt.cb_api import market_order_btc
private_1       |   File "/app/cbt/cb_api.py", line 7, in <module>
private_1       |     max_requests = int(os.getenv("MAX_REQUESTS"))
private_1       | TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'****
```

**Comment by baogorek** [comment]
Gave it a shot here: https://github.com/kjmerf/hello_cb_pro/pull/6
